### ISSUE TITLE
runtests.jl - Tests failed, with Warnings

### ISSUE THREAD

**Issue by rarygit** [vOptSolver/vOptGeneric.jl#1]
Having newly installed on julia v0.6.3 the package vOptGeneric.jl, I would like to understand why the vOptGeneric runtests.jl failed?
Summarised as below:

julia> include("C:/Users/office/.julia/v0.6/vOptGeneric/test/runtests.jl")
Warning: Not solved to optimality, status: Infeasible
Warning: Infeasibility ray (Farkas proof) not available
Test Failed
ERROR: LoadError: There was an error during testing while loading C:\Users\office\.julia\v0.6\vOptGeneric\test\runtests.jl, in expression starting on line 82

Thanks for any assistance with this.

**Comment by gsoleilhac** [comment]
Could you paste the full output ?

**Comment by rarygit** [comment]
Thanks for replying. I reinstalled julia v0.6.3 in the meantime. Full output for v0.6.3 as follows:

julia> using vOptGeneric
INFO: Precompiling module vOptGeneric.

julia> using GLPK ; using GLPKMathProgInterface
INFO: Precompiling module GLPK.
INFO: Precompiling module GLPKMathProgInterface.

julia> include("C:/Users/office/.julia/v0.6/vOptGeneric/test/runtests.jl")
z1 = 8.0, z2 = 9.0. Solving with f2 <= 8.5
WARNING: Solver does not appear to support providing initial feasible solutions.

z1 = 10.0, z2 = 7.0. Solving with f2 <= 6.5
z1 = 11.0, z2 = 5.0. Solving with f2 <= 4.5
z1 = 13.0, z2 = 4.0. Solving with f2 <= 3.5
glp_intopt: optimal basis to initial LP relaxation not provided
Warning: Not solved to optimality, status: Infeasible
Warning: Infeasibility ray (Farkas proof) not available
[8.0, 9.0] : x[1,2]=1 x[2,4]=1 x[4,6]=1
[10.0, 7.0] : x[1,2]=1 x[2,5]=1 x[5,6]=1
[11.0, 5.0] : x[1,2]=1 x[2,6]=1
[13.0, 4.0] : x[1,3]=1 x[3,4]=1 x[4,6]=1
. Solving with f1 >= 918.5 and f2 >= 906.5
. Solving with f1 >= 934.5 and f2 >= 906.5
. Solving with f1 >= 948.5 and f2 >= 906.5
. Solving with f1 >= 949.5 and f2 >= 906.5
. Solving with f1 >= 952.5 and f2 >= 906.5
. Solving with f1 >= 949.5 and f2 >= 909.5
. Solving with f1 >= 948.5 and f2 >= 915.5
. Solving with f1 >= 934.5 and f2 >= 939.5
. Solving with f1 >= 943.5 and f2 >= 939.5
. Solving with f1 >= 934.5 and f2 >= 940.5
. Solving with f1 >= 940.5 and f2 >= 940.5
. Solving with f1 >= 934.5 and f2 >= 943.5
. Solving with f1 >= 935.5 and f2 >= 943.5
. Solving with f1 >= 934.5 and f2 >= 947.5
. Solving with f1 >= 918.5 and f2 >= 971.5
. Solving with f1 >= 927.5 and f2 >= 971.5
. Solving with f1 >= 918.5 and f2 >= 972.5
. Solving with f1 >= 924.5 and f2 >= 972.5
. Solving with f1 >= 918.5 and f2 >= 975.5
solving for objectives [1, 2]
solving for objectives [2, 1]
Test Failed
  Expression: Y_N == [[955.0, 906.0], [918.0, 984.0]]
   Evaluated: Array{Float64,1}[[955.0, 906.0]] == Array{Float64,1}[[955.0, 906.0
], [918.0, 984.0]]
ERROR: LoadError: There was an error during testing
while loading C:\Users\office\.julia\v0.6\vOptGeneric\test\runtests.jl, in expre
ssion starting on line 82

julia>

**Comment by rarygit** [comment]
Thanks

**Comment by rarygit** [comment]
vOptSpecific build OK on windows 8; all tests passed.
vOptGeneric added OK but failed tests on Julia v0.6.4

Output as follows:

INFO: vOptSpecific tests passed

julia> Pkg.test("vOptGeneric")
INFO: Computing test dependencies for vOptGeneric...
INFO: No packages to install, update or remove
INFO: Testing vOptGeneric
z1 = 8.0, z2 = 9.0. Solving with f2 <= 8.5
WARNING: Solver does not appear to support providing initial feasible solutions.

z1 = 10.0, z2 = 7.0. Solving with f2 <= 6.5
z1 = 11.0, z2 = 5.0. Solving with f2 <= 4.5
z1 = 13.0, z2 = 4.0. Solving with f2 <= 3.5
glp_intopt: optimal basis to initial LP relaxation not provided
Warning: Not solved to optimality, status: Infeasible
Warning: Infeasibility ray (Farkas proof) not available
[8.0, 9.0] : x[1,2]=1 x[2,4]=1 x[4,6]=1
[10.0, 7.0] : x[1,2]=1 x[2,5]=1 x[5,6]=1
[11.0, 5.0] : x[1,2]=1 x[2,6]=1
[13.0, 4.0] : x[1,3]=1 x[3,4]=1 x[4,6]=1
. Solving with f1 >= 918.5 and f2 >= 906.5
. Solving with f1 >= 934.5 and f2 >= 906.5
. Solving with f1 >= 948.5 and f2 >= 906.5
. Solving with f1 >= 949.5 and f2 >= 906.5
. Solving with f1 >= 952.5 and f2 >= 906.5
. Solving with f1 >= 949.5 and f2 >= 909.5
. Solving with f1 >= 948.5 and f2 >= 915.5
. Solving with f1 >= 934.5 and f2 >= 939.5
. Solving with f1 >= 943.5 and f2 >= 939.5
. Solving with f1 >= 934.5 and f2 >= 940.5
. Solving with f1 >= 940.5 and f2 >= 940.5
. Solving with f1 >= 934.5 and f2 >= 943.5
. Solving with f1 >= 935.5 and f2 >= 943.5
. Solving with f1 >= 934.5 and f2 >= 947.5
. Solving with f1 >= 918.5 and f2 >= 971.5
. Solving with f1 >= 927.5 and f2 >= 971.5
. Solving with f1 >= 918.5 and f2 >= 972.5
. Solving with f1 >= 924.5 and f2 >= 972.5
. Solving with f1 >= 918.5 and f2 >= 975.5
solving for objectives [1, 2]
solving for objectives [2, 1]
Test Failed
  Expression: Y_N == [[955.0, 906.0], [918.0, 984.0]]
   Evaluated: Array{Float64,1}[[955.0, 906.0]] == Array{Float64,1}[[955.0, 906.0
], [918.0, 984.0]]
ERROR: LoadError: There was an error during testing
while loading C:\Users\office\.julia\v0.6\vOptGeneric\test\runtests.jl, in expre
ssion starting on line 82
=============================[ ERROR: vOptGeneric ]=============================


failed process: Process(`'C:\Users\office\AppData\Local\Julia-0.6.4\bin\julia.ex
e' -Cgeneric '-JC:\Users\office\AppData\Local\Julia-0.6.4\lib\julia\sys.dll' --c
ompile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --c
ompilecache=yes 'C:\Users\office\.julia\v0.6\vOptGeneric\test\runtests.jl'`, Pro
cessExited(1)) [1]

================================================================================

INFO: No packages to install, update or remove
ERROR: vOptGeneric had test errors

julia>

**Comment by gsoleilhac** [comment]
I couldn't reproduce this on Julia v0.6.4 but I found the same error while upgrading the code for julia v1.0.
It seems to be due to the values used to deactivate the constraints (JuMP doesn't allow constraint deletion yet) ;  changing the 1e18 to 1e16 in src/algorithms.jl fixed the problem for me. I will provide an update soon once I'm done updating to 1.0

**Comment by rarygit** [comment]
Ok, looking forward to the v1.0 updating! I will look at the algorithms.jl work-around you described. 28.10.2018, 23:05, "Gauthier Soleilhac" <notifications@github.com>:I couldn't reproduce this on Julia v0.6.4 but I found the same error while upgrading the code for julia v1.0.It seems to be due to the values used to deactivate the constraints (JuMP doesn't allow constraint deletion yet) ; changing the 1e18 to 1e16 in src/algorithms.jl fixed the problem for me. I will provide an update soon once I'm done updating to 1.0—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by rarygit** [comment]
The latest update to vOptGeneric passed all tests on Windows 8, Julia v1.0.1.

Thanks for the update!
