### ISSUE TITLE
Converting a JuMP model into a vOptGeneric

### ISSUE THREAD

**Issue by boiro9** [vOptSolver/vOptGeneric.jl#12]
I have a MILP formulated as a JuMP model, but I create it reading an mps file so I have not formulated it directly in Julia. I want to add to this problem a new objective function and then use vOptGeneric to solve it. I do not know how to convert the JuMP model to a vOptGeneric model object. My first idea was to create an empty vOptGeneric model, and then update it iterating over the objects of the JuMP model (variables, objective function and constraints), but I have a lot of problems to do it. I would really apprecciate any help.

**Comment by gsoleilhac** [comment]
We don't have that functionnality but it should be fairly easy to implement and certainly useful.

As a workaround you can use some of the internals of vOptGeneric to do that by modifying the model in-place :

```
m = JuMP.Model(Cbc.Optimizer)
@variable(m, ...)
@objective(m, Min, ...)

m.ext[:vOpt] = vOptGeneric.vOptData()
push!(m.ext[:vOpt].objs, JuMP.objective_function(m))
push!(m.ext[:vOpt].objSenses, JuMP.objective_sense(m))

@addobjective(m, Max, ...)
```

**Comment by boiro9** [comment]
Thank you very much @gsoleilhac, this is exactly what I want. Related to this, but with respect to JuMP, I have the following question that may be you can help me. 

Suppose that I have the following toy example in JuMP:
```
model = Model();
set_optimizer(model, GLPK.Optimizer);
@variable(model, 0 <= x <= 2)
@variable(model, 0 <= y <= 30)
@objective(model, Max, 5x + 3 * y)
@constraint(model, con, 1x + 5y <= 3)
```

And now If I want to define a new problem with the same variables, I can do something like:
```
m = Model();
vars = all_variables(model)
for i in 1:length(vars)
    @variable(m,base_name=JuMP.name(vars[i]))
end
```
Suppose that I want to define exacly the same constraint "con" in this new model, I tried to do something similar but I have not success. In fact, I tried to do it but more general, something like:
```
cons = list_of_constraint_types(model)
for (i,v) in enumerate(cons)
    println(i," : ",v[1]," : ", v[2])
    all_cc = all_constraints(model,v[1],v[2])
    for j in 1:length(all_cc)
        println(all_cc[j])
        con = constraint_object(all_cc[j])
        println(JuMP.name(all_cc[j]), " : ",con.func)
        #@constraint(m, JuMP.name(con), con.func)
    end
end
```
but I do not know how to call the "@contraint" method correctly. I also tried to use the func and set method to define the constraint, something like: 
`@constraint(m, JuMP.name(con), con.func<=con.set)`
but this also does not work.

I am new to Julia, so I am sorry if they are silly questions, but I want to implement a generic algorithm, so I need to understand how to manipulate the JuMP model. If you see a better way to do this kind of things, and you can give me some references, I would really appreciate it.

**Comment by gsoleilhac** [comment]
> something like: `@constraint(m, JuMP.name(con), con.func<=con.set)`

This doesn't work because the `@constraint` macro expects a name (directly as a `Symbol`, not as a variable or a function call)
See for example : 
```
m=Model();
@variable(m, x >= 0);
name = "foo";
constraint = @constraint(m, name, x <= 5);
JuMP.name(constraint) # this prints "name", not "foo"
```

I'm by no means a JuMP expert, so you might have better answers on their github, or their [Gitter chat room](https://gitter.im/JuliaOpt/JuMP-dev) but here is how I would do it : 
```
cons = list_of_constraint_types(model)
for (i, (functype, settype)) in enumerate(cons)
    println(i," : ", functype, " : ", settype)
    all_cc = all_constraints(model, functype, settype)
    for c in all_cc
        model_con = constraint_object(c)
        m_con = @constraint(m, copy(model_con.func, m) in model_con.set)
        JuMP.set_name(m_con, JuMP.name(c))
        println(m_con)
    end
end
```

Another option could be to simply copy the model and `delete!` the constraints you dont need

**Comment by boiro9** [comment]
Thank you very much for your help!
