### ISSUE TITLE
violated constraint

### ISSUE THREAD

**Issue by saesf** [vOptSolver/vOptGeneric.jl#4]
hi,
i use zimpl modeling language and a 3rd party python script to create a mop file for my optimization model. when i used this file with solver to minimize two objectives, both objectives became zero in results, which is impossible because of constraint 3.can anyone help me to figure out the problem? zimpl model and mop file are attached
[model5m.zpl.txt](https://github.com/vOptSolver/vOptGeneric.jl/files/3289171/model5m.zpl.txt)

[model5m.mop.txt](https://github.com/vOptSolver/vOptGeneric.jl/files/3289175/model5m.mop.txt)

**Comment by gsoleilhac** [comment]
Hi,
I think there's something wrong with your .mop file : in the ROWS section ~2300 constraints are declared, but in the RHS section, only the right-hand-side of 24 constraints are defined.

This is problematic for equality constraints because they are modelled as RHS <= constraint_terms <= RHS and by default they are bounded by -Inf <= terms <= +Inf, which doesn't seem to be supported by JuMP.
(If you try to print the model you get an error : `ERROR: 'Free' constraint sense not supported` when trying to print the constraints)

**Comment by saesf** [comment]
thanks for reply.
you are right. apparently zimpl change constraints equation to make their RHS zero (if possible) and does not add RHS equal Zero in RHS section. is there any way to chage default value of RHS in JuMP?or i should set RHS rows myself?

**Comment by gsoleilhac** [comment]
I'm not sure if you can do it in JuMP because the .mop file contains `<=`, `>=` and `==` constraints, but once they have been parsed without rhs, you don't know if you need to set the constraint's lower bound, upper bound or both.

**Comment by saesf** [comment]
i changed mop file myself and added RHS 0 line for all contraint. print(m) does not give any error but when i try solving the problem, solve method print lots of following error messages and it does not stop.
`Error: basis matrix is singular to working precision (cond = 5.13e+016)`
`z1 = 0.0, z2 = 1.0. Solving with f2 <= 0.999 `
`Error: unable to factorize the basis matrix (1) `
`z1 = 0.0, z2 = 1.0. Solving with f2 <= 0.999`
do you know what does this mean?
[model5m.mop.txt](https://github.com/vOptSolver/vOptGeneric.jl/files/3291123/model5m.mop.txt)

**Comment by gsoleilhac** [comment]
Hmm no, could be related to the solver you're using ? I just tested your example with Cbc and I dont get any error

**Comment by saesf** [comment]
i'm using GLPKSolverMIP, i changed it to Cbc and now it works fine and results are correct. but it's a little slow. do you have any advice on how to make solve method faster?
