### ISSUE TITLE
key not found error

### ISSUE THREAD

**Issue by saesf** [vOptSolver/vOptGeneric.jl#8]
when i try to parse attached mop file using parseMOP
`m = parseMOP("final.mop" , solver=GurobiSolver() )`

i get following error:

`ERROR: KeyError: key "flo@118f\r" not found`
`Stacktrace:`
`[1] getindex at .\dict.jl:474 [inlined]`
` [2] (::vOptGeneric.##4#5{JuMP.Model})(::IOStream) at C:\Users\sajad esfandiari\.julia\v0.6\vOptGeneric\src\MOP.jl:316`
` [3] open(::vOptGeneric.##4#5{JuMP.Model}, ::String) at .\iostream.jl:152`
` [4] #parseMOP#3 at C:\Users\sajad esfandiari\.julia\v0.6\vOptGeneric\src\MOP.jl:185 [inlined]`
` [5] (::vOptGeneric.#kw##parseMOP)(::Array{Any,1}, ::vOptGeneric.#parseMOP, ::String) at .\<missing>:0`

can anyone help me to find the cause of this problem?
[final.mop.txt](https://github.com/vOptSolver/vOptGeneric.jl/files/3313284/final.mop.txt)

**Comment by xgandibleux** [comment]
The current version of vOptGeneric is working with julia 1.x and JuMP 0.18.
Are you in this configuration?

**Comment by gsoleilhac** [comment]
How did you generate the mop file ?
The "\r" at the end of the variable name suggest it's an encoding issue but I couldn't reproduce it with your file.

As @xgandibleux suggested, you should update to the last julia release 1.1.x ; the last vOptGeneric version is not compatible with julia 0.6

**Comment by saesf** [comment]
i updated Julia and now every things seems to work without any problem. 
thanks for your help @xgandibleux and @gsoleilhac
